name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set version from tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Inject version into script
        run: |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s/^VERSION=\"dev\"/VERSION=\"${VERSION#v}\"/" autocommit.sh
          else
            sed -i "s/^VERSION=\"dev\"/VERSION=\"${VERSION#v}\"/" autocommit.sh
          fi

      - name: Make script executable
        run: chmod +x autocommit.sh

      - name: Build tar.gz archive
        run: |
          mkdir -p dist
          cp autocommit.sh dist/autocommit
          tar -czf autocommit-${VERSION#v}.tar.gz -C dist autocommit
          sha256sum autocommit-${VERSION#v}.tar.gz > autocommit-${VERSION#v}.tar.gz.sha256

      - name: Build .deb package
        run: |
          mkdir -p pkg/usr/local/bin
          cp autocommit.sh pkg/usr/local/bin/autocommit
          chmod +x pkg/usr/local/bin/autocommit
          mkdir -p pkg/DEBIAN
          bash -c 'cat <<EOF > pkg/DEBIAN/control
Package: autocommit
Version: ${VERSION#v}
Section: utils
Priority: optional
Architecture: all
Maintainer: Msonc
Description: A tiny Git auto-committer script in Bash
Depends: git
EOF'
          dpkg-deb --build pkg autocommit_${VERSION#v}_all.deb

      - name: Generate Homebrew formula
        run: |
          SHA=$(cut -d ' ' -f1 autocommit-${VERSION#v}.tar.gz.sha256)
          bash -c "cat <<EOF > autocommit.rb
class Autocommit < Formula
  desc \"Tiny Git auto-committer script\"
  homepage \"https://github.com/${{ github.repository }}\"
  url \"https://github.com/${{ github.repository }}/archive/refs/tags/${VERSION}.tar.gz\"
  sha256 \"$SHA\"
  license \"MIT\"

  def install
    bin.install \"autocommit.sh\" => \"autocommit\"
  end
end
EOF"

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          name: "Auto Committer ${{ env.VERSION }}"
          tag_name: ${{ env.VERSION }}
          files: |
            autocommit-${{ env.VERSION#v }}.tar.gz
            autocommit-${{ env.VERSION#v }}.tar.gz.sha256
            autocommit_${{ env.VERSION#v }}_all.deb
            autocommit.rb
