name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    name: Build and Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set version from tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Inject version into script
        run: |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s/^VERSION=\"dev\"/VERSION=\"${VERSION#v}\"/" autocommit.sh
          else
            sed -i "s/^VERSION=\"dev\"/VERSION=\"${VERSION#v}\"/" autocommit.sh
          fi

      - name: Make script executable
        run: chmod +x autocommit.sh

      - name: Build tar.gz archive
        run: |
          mkdir -p dist
          cp autocommit.sh dist/autocommit
          tar -czf autocommit-${VERSION#v}.tar.gz -C dist autocommit
          sha256sum autocommit-${VERSION#v}.tar.gz > autocommit-${VERSION#v}.tar.gz.sha256

      - name: Build .deb package
        run: |
          mkdir -p pkg/usr/local/bin
          cp autocommit.sh pkg/usr/local/bin/autocommit
          chmod +x pkg/usr/local/bin/autocommit
          mkdir -p pkg/DEBIAN
          echo "Package: autocommit" > pkg/DEBIAN/control
          echo "Version: ${VERSION#v}" >> pkg/DEBIAN/control
          echo "Section: utils" >> pkg/DEBIAN/control
          echo "Priority: optional" >> pkg/DEBIAN/control
          echo "Architecture: all" >> pkg/DEBIAN/control
          echo "Maintainer: Msonc" >> pkg/DEBIAN/control
          echo "Description: A tiny Git auto-committer script in Bash" >> pkg/DEBIAN/control
          echo "Depends: git" >> pkg/DEBIAN/control
          dpkg-deb --build pkg autocommit_${VERSION#v}_all.deb

      - name: Generate Homebrew formula
        run: |
          SHA=$(cut -d ' ' -f1 autocommit-${VERSION#v}.tar.gz.sha256)
          echo "class Autocommit < Formula" > autocommit.rb
          echo "  desc \"Tiny Git auto-committer script\"" >> autocommit.rb
          echo "  homepage \"https://github.com/${{ github.repository }}\"" >> autocommit.rb
          echo "  url \"https://github.com/${{ github.repository }}/archive/refs/tags/${VERSION}.tar.gz\"" >> autocommit.rb
          echo "  sha256 \"$SHA\"" >> autocommit.rb
          echo "  license \"MIT\"" >> autocommit.rb
          echo "" >> autocommit.rb
          echo "  def install" >> autocommit.rb
          echo "    bin.install \"autocommit.sh\" => \"autocommit\"" >> autocommit.rb
          echo "  end" >> autocommit.rb
          echo "end" >> autocommit.rb

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          name: "Auto Committer ${{ env.VERSION }}"
          tag_name: ${{ env.VERSION }}
          files: |
            autocommit-${{ env.VERSION }}.tar.gz
            autocommit-${{ env.VERSION }}.tar.gz.sha256
            autocommit_${{ env.VERSION }}_all.deb
            autocommit.rb

      - name: Push updated formula to tap repo
        run: |
          git config --global user.name "autocommit bot"
          git config --global user.email "bot@autocommit.local"

          git clone https://x-access-token:${{ secrets.TAP_GITHUB_TOKEN }}@github.com/CraftyRobot/homebrew-autocommit.git tap
          cp autocommit.rb tap/Formula/autocommit.rb
          cd tap
          git add Formula/autocommit.rb
          git commit -m "Update autocommit formula to $VERSION"
          git push origin main
